services:
         db:
           image: mongo
           container_name: db
           restart: always
           environment:
             - MONGO_INITDB_ROOT_USERNAME=neojhon
             - MONGO_INITDB_ROOT_PASSWORD=368091
           ports:
             - "27017:27017"
           volumes:
             - ./MongoDB/dbdata:/data/db